[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.solana/CMADP5F3EPYDZC2KBBBC1GmGi1arFEyfozpA8B3rwLWW.json"

[workspace]
members = [
  "program",
]