[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[programs.localnet]
candy_guard = "CMAGAKJ67e9hRZgfC5SFTbZH8MgEmtqazKXjmkaJjWTJ"

[provider]
cluster = "devnet"
wallet = "~/wallet.json"

[workspace]
members = [
  "program",
]