[registry]
url = "https://anchor.projectserum.com"

[programs.localnet]
candy_machine_core = "CMACYFENjoBMHzapRXyo1JZkVS6EtaDDzkjMrmQLvr4J"

[provider]
cluster = "devnet"
wallet = "~/wallet.json"

[workspace]
members = [
  "program",
]
